---
version: "3.8"
services:
  test:
    build:
      target: test
      context: .

  cli:
    build:
      target: cli
      context: .
    environment:
      ANSIBLE_COLLECTIONS_PATH: /usr/share/ansible/collections
      ANSIBLE_ROLES_PATH: /usr/share/ansible/roles
    image: ${COMMIT_IMAGE:-git-enterprise-jc.onefiserv.net:4443/fts-san/sane/rundeck/lb/f5-as3:cli}
